# Build stage
FROM node:18 AS builder

WORKDIR /app

# Copy everything
COPY . .

# Move into frontend directory
WORKDIR /app/frontend

# Install dependencies and build
RUN npm install
RUN npm run build

# Inject env.js
RUN echo 'window.RUNTIME_ENV = { REACT_APP_SERVERURL: "https://keysign.usekeys.co" };' > build/env.js

# Serve stage
FROM node:18-alpine

WORKDIR /app

RUN npm install -g serve

# Copy built frontend
COPY --from=builder /app/frontend/build ./build

EXPOSE 3000

CMD ["serve", "-s", "build", "-l", "3000"]
