FROM node:22 AS builder
WORKDIR /app
COPY . .
WORKDIR /app/apps/OpenSign
RUN npm install
RUN npm run build
RUN echo 'window.RUNTIME_ENV = { REACT_APP_SERVERURL: "http://keysign.usekeys.co" };' > build/env.js

FROM node:22-slim
WORKDIR /app
RUN npm install -g serve
COPY --from=builder /app/apps/OpenSign/build ./build
EXPOSE 3000
CMD ["serve", "-s", "build", "-l", "3000"]
